version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: banku-mongodb-openbanking
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: banku
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: banku-openbanking
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: