spring:
  application:
    name: banku-openbanking-service
  profiles:
    active: local
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
  kafka:
    consumer:
      group-id: banku-user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: ${jwt.secret}

server:
  port: 8082

logging:
  level:
    com.banku.openbankingservice: DEBUG
    org.springframework.security: INFO 

plaid:
  client-id: ${plaid.client-id}
  secret: ${plaid.secret}
  env: ${plaid.env}
